services:
  develop:
    build:
      context: .
      dockerfile: dockerfile
      # Please note that UID and GID are set to 501, 
      # which is the my UID and GID on the host machine.
      args:
        - UID=${UID:-501}
        - GID=${GID:-501}
    volumes:
      - .:/home/oversir/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY:-~/.Xauthority}:/tmp/.Xauthority
    environment:
      - DISPLAY=host.docker.internal:0
    network_mode: "host"
    stdin_open: true
    tty: true
